language: python
python:
  - "3.7"
  - "3.6"
  
install: "pip install -r requirement.txt"
script: 
- coverage run test.py
- docker image build -t 500900260/cps847-a2 



after_success: 
- bash <(curl -s https://codecov.io/bash)
- docker push 500900260/cps847-a2
- docker ps -a
